### PR TITLE
Add &FCP block required by QE 6.8

### PR DESCRIPTION
**Pull request by afonari**
There is a new &FCP block required to set fcp_mu: https://gitlab.com/QEF/q-e/-/blob/develop/PW/examples/ESM_example/run_example_FCP#L108

Also lfcpopt is replaced with lfcp (https://github.com/QEF/qeschema/issues/13).

### CODE REVIEW

**Comment by giannozz** [comment]
&FCP ... / should not be compulsory, I guess

**Comment by afonari** [comment]
> &FCP ... / should not be compulsory, I guess

Sure, updated so that &FCP/ block is only printed if it has any members (like `fcp_mu`).

**Comment by afonari** [comment]
CI failed because: `Job has been terminated due to insufficient credits balance`. Tests passed on Linux.

**Comment by giannozz** [comment]
Maybe there are time limits we have exceeded ... ? or maybe it is a transient problem.

**Pull request merged**
